import bcrypt from 'bcrypt';
import { env } from '../config/env.js';
import { query } from '../config/db.js';
import { AppError } from '../utils/AppError.js';
const map = (r) => ({ id: r.id, fullName: r.full_name, email: r.email, role: r.role, createdAt: r.created_at });
const duplicate = (e) => e.code === '23505' && e.constraint === 'users_email_key';
export async function listUsers() { const { rows } = await query('SELECT id, full_name, email, role, created_at FROM users ORDER BY created_at ASC'); return rows.map(map); }
export async function createUser(v) { try { const hash = await bcrypt.hash(v.password, env.BCRYPT_ROUNDS); const { rows } = await query('INSERT INTO users (full_name, email, password_hash, role) VALUES ($1,$2,$3,$4) RETURNING id, full_name, email, role, created_at', [v.fullName, v.email, hash, v.role]); return map(rows[0]); } catch (e) { if (duplicate(e)) throw new AppError(409, 'DUPLICATE_EMAIL', 'A user with this email already exists.'); throw e; } }
export async function updateUser(id, v) { const fields = { fullName: 'full_name', email: 'email', role: 'role' }; const set = []; const vals = []; for (const [k,c] of Object.entries(fields)) if (v[k] !== undefined) { vals.push(v[k]); set.push(`${c} = $${vals.length}`); } if (v.password) { vals.push(await bcrypt.hash(v.password, env.BCRYPT_ROUNDS)); set.push(`password_hash = $${vals.length}`); } vals.push(id); try { const { rows } = await query(`UPDATE users SET ${set.join(', ')} WHERE id = $${vals.length} RETURNING id, full_name, email, role, created_at`, vals); if (!rows[0]) throw new AppError(404, 'USER_NOT_FOUND', 'User not found.'); return map(rows[0]); } catch (e) { if (duplicate(e)) throw new AppError(409, 'DUPLICATE_EMAIL', 'A user with this email already exists.'); throw e; } }
export async function deleteUser(id, currentUserId) { if (id === currentUserId) throw new AppError(409, 'CANNOT_DELETE_SELF', 'You cannot delete your own account.'); const events = await query('SELECT 1 FROM events WHERE created_by = $1 LIMIT 1', [id]); if (events.rowCount) throw new AppError(409, 'USER_HAS_EVENTS', 'Users who created events cannot be deleted.'); const result = await query('DELETE FROM users WHERE id = $1', [id]); if (!result.rowCount) throw new AppError(404, 'USER_NOT_FOUND', 'User not found.'); }
