import React, { useEffect, useState } from 'react';
import './styles.css';

const base = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
async function api(path, token, options = {}) { const response = await fetch(base + path, { ...options, headers: { 'content-type': 'application/json', ...(token && { authorization: `Bearer ${token}` }), ...options.headers } }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Request failed'); return body; }

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('eventhub_token'));
  const [page, setPage] = useState('dashboard'); const [data, setData] = useState({}); const [message, setMessage] = useState('');
  const load = async () => { if (!token) return; try { const [me, dashboard, events, participants] = await Promise.all([api('/auth/me', token), api('/dashboard', token), api('/events', token), api('/participants', token)]); setData({ user: me.user, dashboard, events: events.events, participants: participants.participants }); } catch (error) { setMessage(error.message); setToken(null); localStorage.removeItem('eventhub_token'); } };
  useEffect(() => { load(); }, [token]);
  if (!token) return <Login onLogin={async (email, password) => { const result = await api('/auth/login', null, { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('eventhub_token', result.token); setToken(result.token); }} message={message} />;
  const submit = async (event, path) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (values.maxParticipants) values.maxParticipants = Number(values.maxParticipants); if (values.eventDate) values.eventDate = new Date(values.eventDate).toISOString(); if (values.phone === '') values.phone = null; try { await api(path, token, { method: 'POST', body: JSON.stringify(values) }); setMessage('Saved successfully.'); event.currentTarget.reset(); load(); } catch (error) { setMessage(error.message); } };
  const action = async (path, method = 'PATCH', body) => { try { await api(path, token, { method, ...(body && { body: JSON.stringify(body) }) }); setMessage('Updated successfully.'); load(); } catch (error) { setMessage(error.message); } };
  return <div className="app"><aside><h1>EventHub</h1><small>BACK-OFFICE</small>{['dashboard','events','participants','registrations'].map((name) => <button className={page === name ? 'active' : ''} onClick={() => setPage(name)} key={name}>{name}</button>)}<footer>{data.user?.fullName}<button onClick={() => { localStorage.removeItem('eventhub_token'); setToken(null); }}>Sign out</button></footer></aside><main><header>CULTURAL OPERATIONS <b>{data.user?.role}</b></header>{message && <p className="notice">{message}</p>}{page === 'dashboard' && <Dashboard data={data.dashboard}/>} {page === 'events' && <Events events={data.events || []} submit={submit} action={action}/>} {page === 'participants' && <Participants participants={data.participants || []} submit={submit} action={action}/>} {page === 'registrations' && <Registrations events={data.events || []} participants={data.participants || []} submit={submit}/>}</main></div>;
}
function Login({ onLogin, message }) { return <div className="login"><section><p>EVENTHUB · INTERNAL OPERATIONS</p><h1>Curating moments<br/>that resonate.</h1></section><form onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await onLogin(f.get('email'), f.get('password')); } catch (error) {} }}><h2>Welcome back</h2><input name="email" type="email" defaultValue="kenza.benjelloun@eventhub.ma" required/><input name="password" type="password" defaultValue="EventHub2025!" required/><button>Sign in</button>{message && <p className="notice">{message}</p>}</form></div>; }
function Dashboard({ data = {} }) { return <><p className="eyebrow">CURATORIAL PORTFOLIO</p><h1>Cultural Intelligence & Manifest</h1><div className="cards"><Card label="Total events" value={data.totalEvents}/><Card label="Published events" value={data.publishedEvents}/><Card label="Registrations today" value={data.registrationsToday}/></div><section className="panel"><h2>Capacity utilization</h2>{(data.topEvents || []).map((e) => <article className="item" key={e.id}><b>{e.title}</b><span>{e.registered} / {e.maxParticipants}</span><i><em style={{ width: `${e.fillRate * 100}%` }}/></i></article>)}</section></>; }
function Card({ label, value }) { return <article className="card"><small>{label}</small><strong>{value ?? '—'}</strong></article>; }
function Events({ events, submit, action }) { return <><h1>Events Directory</h1><div className="columns"><section className="panel">{events.map((e) => <article className="item" key={e.id}><div><b>{e.title}</b><small>{new Date(e.eventDate).toLocaleString()} · {e.location}</small>{e.status === 'draft' && <button onClick={() => action(`/events/${e.id}/status`, 'PATCH', { status: 'published' })}>Publish</button>}{e.status !== 'cancelled' && <button onClick={() => window.confirm(`Cancel ${e.title} and registrations?`) && action(`/events/${e.id}/status`, 'PATCH', { status: 'cancelled' })}>Cancel</button>}</div><span className={e.status}>{e.status} · {e.registeredCount}/{e.maxParticipants}</span></article>)}</section><form className="panel form" onSubmit={(e) => submit(e, '/events')}><h2>Create event</h2><input name="title" placeholder="Title" required/><textarea name="description" placeholder="Description"/><input name="location" placeholder="Location" required/><input name="eventDate" type="datetime-local" required/><input name="maxParticipants" type="number" min="1" placeholder="Capacity" required/><button>Create draft</button></form></div></>; }
function Participants({ participants, submit, action }) { return <><h1>Participants</h1><div className="columns"><section className="panel">{participants.map((p) => <article className="item" key={p.id}><div><b>{p.fullName}</b><small>{p.email}</small><button onClick={() => window.confirm(`Delete ${p.fullName}?`) && action(`/participants/${p.id}`, 'DELETE')}>Delete</button></div><span>{p.phone || '—'}</span></article>)}</section><form className="panel form" onSubmit={(e) => submit(e, '/participants')}><h2>Add participant</h2><input name="fullName" placeholder="Full name" required/><input name="email" type="email" placeholder="Email" required/><input name="phone" placeholder="Phone"/><button>Save</button></form></div></>; }
function Registrations({ events, participants, submit }) { return <><h1>Issue registration</h1><form className="panel form" onSubmit={(e) => submit(e, '/registrations')}><select name="participantId">{participants.map((p) => <option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select name="eventId">{events.filter((e) => e.status === 'published').map((e) => <option key={e.id} value={e.id}>{e.title}</option>)}</select><button>Confirm registration</button></form></>; }
